#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'beeswax_types'

module Impala
  module Protocol
    module Beeswax
    end
  end
end
