#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'status_types'
require 'beeswax_types'


module Impala
  module Protocol
    module TImpalaQueryOptions
      ABORT_ON_ERROR = 0
      MAX_ERRORS = 1
      DISABLE_CODEGEN = 2
      BATCH_SIZE = 3
      NUM_NODES = 4
      MAX_SCAN_RANGE_LENGTH = 5
      MAX_IO_BUFFERS = 6
      NUM_SCANNER_THREADS = 7
      ALLOW_UNSUPPORTED_FORMATS = 8
      DEFAULT_ORDER_BY_LIMIT = 9
      VALUE_MAP = { 0 => "ABORT_ON_ERROR", 1 => "MAX_ERRORS", 2 => "DISABLE_CODEGEN", 3 => "BATCH_SIZE", 4 => "NUM_NODES", 5 => "MAX_SCAN_RANGE_LENGTH", 6 => "MAX_IO_BUFFERS", 7 => "NUM_SCANNER_THREADS", 8 => "ALLOW_UNSUPPORTED_FORMATS", 9 => "DEFAULT_ORDER_BY_LIMIT" }
      VALID_VALUES = Set.new([ABORT_ON_ERROR, MAX_ERRORS, DISABLE_CODEGEN, BATCH_SIZE, NUM_NODES, MAX_SCAN_RANGE_LENGTH, MAX_IO_BUFFERS, NUM_SCANNER_THREADS, ALLOW_UNSUPPORTED_FORMATS, DEFAULT_ORDER_BY_LIMIT]).freeze
    end

    class TInsertResult
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ROWS_APPENDED = 1

      FIELDS = {
      ROWS_APPENDED => { :type => ::Thrift::Types::MAP, :name => 'rows_appended', :key => { :type => ::Thrift::Types::STRING }, :value => { :type => ::Thrift::Types::I64 } }
      }

      def struct_fields; FIELDS; end

      def validate
        raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field rows_appended is unset!') unless @rows_appended
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
