#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 't_c_l_i_service'
require 'impala_service_types'

module Impala
  module Protocol
    module ImpalaHiveServer2Service
      class Client < ::Impala::Protocol::Hive::TCLIService::Client 
        include ::Thrift::Client

      end

      class Processor < ::Impala::Protocol::Hive::TCLIService::Processor 
        include ::Thrift::Processor

      end

      # HELPER FUNCTIONS AND STRUCTURES

    end

  end
end
