#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'java_constants_types'

module Impala
  module Protocol
    NUM_NODES_ALL = 0

    NUM_NODES_ALL_RACKS = -1

    INVALID_PLAN_NODE_ID = -1

    DEFAULT_PARTITION_ID = -1

    COMPRESSION_MAP = {
    %q"" =>           0,
    %q"none" =>           0,
    %q"deflate" =>           1,
    %q"gzip" =>           2,
    %q"bzip2" =>           3,
    %q"snappy" =>           4,
    }

    DEFAULT_QUERY_OPTIONS = {
    0 => %q"false",
    1 => %q"0",
    2 => %q"false",
    3 => %q"0",
    4 => %q"0",
    5 => %q"0",
    6 => %q"0",
    7 => %q"0",
    8 => %q"false",
    9 => %q"-1",
    }

  end
end
